# generated by projio init
PYTHON  ?= python
DATALAD ?= datalad
MSG     ?= Update

-include .projio/projio.mk


.PHONY: test build check publish-test publish clean

test:
	PYTHONPATH=src $(PYTHON) -m pytest tests -q

build:
	$(PYTHON) -m build

check:
	$(PYTHON) -m twine check dist/*

publish-test:
	$(PYTHON) -m twine upload --repository testpypi dist/*

publish:
	$(PYTHON) -m twine upload dist/*

clean:
	rm -rf build dist .pytest_cache .mypy_cache src/*.egg-info
