# generated by projio init
PYTHON  ?= python
DATALAD ?= datalad
PUBLISH ?= /storage2/arash/infra/bin/publish_pypi.sh
MSG     ?= Update

-include .projio/projio.mk


.PHONY: test build check publish-test publish clean

test:
	PYTHONPATH=src $(PYTHON) -m pytest tests -q

build:
	$(PYTHON) -m build

check:
	$(PYTHON) -m twine check dist/*

publish:
	$(PUBLISH) .

publish-test:
	$(PUBLISH) --test .

clean:
	rm -rf build dist .pytest_cache .mypy_cache src/*.egg-info
