"""Pipeline docs collection: two-phase export-then-collect.

Flow authors write docs next to their pipeline code::

    code/pipelines/denoise/
      docs/
        overview.md
        mod-smoothing.md
      notebooks/
        notebook.yml
        demo/.src/analysis.py

``docs_collect`` assembles them into ``docs/pipelines/<flow>/``
for MkDocs, and ``docs_nav`` emits a YAML nav fragment.

**Two-phase design:**

1. **Export** — component-owned functions generate artifacts into
   ``{flow}/.build/`` (DAG SVGs, notebook HTML). Each component owns
   its export logic; ``docs_collect`` just calls them.
2. **Collect** — pure file copiers assemble ``.build/`` outputs,
   hand-written docs, and reports into ``docs/pipelines/<flow>/``.

The source tree (``code/pipelines/<flow>/docs/``) is read-only during
collection. ``docs/pipelines/`` is a build artifact (gitignored).
Collected files carry a source-path header; never edit them directly.

**Convention:** The flow landing page is ``docs/index.md``.  Legacy
``docs/overview.md`` is accepted as a fallback (renamed to ``index.md``
during collection when no source ``index.md`` exists).
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

import yaml
from pydantic import BaseModel


_GENERATED_HEADER = (
    "<!-- DO NOT EDIT — this file is collected by pipeio docs_collect.\n"
    "     Source: {source}\n"
    "     Edit the source file, then re-run docs_collect. -->\n\n"
)

_AUTO_GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by pipeio docs_collect — do not edit. -->\n\n"
)


_BARE_DIR_LINK_RE = re.compile(r"\]\(([^)]+)/\)")
"""Matches markdown links ending with a bare directory slash, e.g. ``](foo/)``."""

_MERMAID_CLICK_RE = re.compile(
    r'(click\s+\w+\s+(?:href\s+)?)"(?!\.\./)(?!https?://)([^"]+)"'
)
"""Matches mermaid click directives with bare relative URLs."""


def _normalize_dir_links(text: str) -> str:
    """Rewrite bare directory links ``](dir/)`` → ``](dir/index.md)``."""
    return _BARE_DIR_LINK_RE.sub(r"](\1/index.md)", text)


def _rewrite_mermaid_click_links(text: str) -> str:
    """Prefix bare relative mermaid click-link URLs with ``../``.

    ``architecture.md`` is served at ``/pipelines/architecture/`` so bare
    paths like ``"preprocess_ieeg/"`` would resolve to
    ``/pipelines/architecture/preprocess_ieeg/`` instead of
    ``/pipelines/preprocess_ieeg/``.  Adding ``../`` fixes the resolution.
    """
    return _MERMAID_CLICK_RE.sub(r'\1"../\2"', text)


def _copy_with_header(src: Path, dst: Path, root: Path) -> None:
    """Copy a file, prepending a source-path header for markdown files."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.suffix == ".md":
        text = src.read_text(encoding="utf-8")
        text = _normalize_dir_links(text)
        rel = src.relative_to(root)
        header = _GENERATED_HEADER.format(source=rel)
        dst.write_text(header + text, encoding="utf-8")
    else:
        shutil.copy2(src, dst)


class PublishConfig(BaseModel):
    """Flow-level publish config (``publish.yml``)."""

    dag: bool = False
    report: bool = False
    report_archive: bool = False
    scripts: bool = False

    @classmethod
    def from_yaml(cls, path: Path) -> PublishConfig:
        with open(path) as fh:
            raw = yaml.safe_load(fh) or {}
        return cls(**raw)


# ---------------------------------------------------------------------------
# Collector protocol + context
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class CollectContext:
    """Per-flow context passed to exporters and collectors."""

    entry: Any  # FlowEntry from registry (Any to avoid circular import)
    flow_dir: Path  # absolute path to flow code directory
    target: Path  # output dir: docs/pipelines/{flow}/
    root: Path  # project root
    publish: PublishConfig  # from publish.yml (defaults if absent)

    @property
    def build_dir(self) -> Path:
        """Per-flow build directory for exported artifacts."""
        return self.flow_dir / ".build"


class Collector(Protocol):
    """Interface for artifact collectors (phase 2 — pure copiers)."""

    def collect(self, ctx: CollectContext) -> list[str]: ...


# ---------------------------------------------------------------------------
# Phase 1: Export functions — generate artifacts into .build/
# ---------------------------------------------------------------------------

def export_dag(ctx: CollectContext) -> str | None:
    """Generate DAG SVG into ``{flow}/.build/dag.svg``.

    Uses snakemake rulegraph + graphviz. Returns the output path on
    success, or None if generation was skipped or failed.
    """
    snakefile = ctx.flow_dir / "Snakefile"
    if not snakefile.exists():
        return None

    try:
        dag_svg = _generate_dag_svg(ctx.root, ctx.entry, snakefile)
    except Exception:
        return None  # non-fatal: DAG generation is best-effort

    if not dag_svg:
        return None

    out = ctx.build_dir / "dag.svg"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(dag_svg, encoding="utf-8")
    return str(out)


def export_notebooks(ctx: CollectContext) -> list[str]:
    """Export publishable notebook HTML/MyST into ``{flow}/.build/notebooks/``.

    Reads ``notebook.yml``, filters explore/investigate notebooks, and
    converts publishable entries via nbconvert. Also generates an
    ``index.md`` listing in the build directory.

    Returns list of exported file paths.
    """
    nb_cfg_path = ctx.flow_dir / "notebooks" / "notebook.yml"
    if not nb_cfg_path.exists():
        return []

    from pipeio.notebook.config import NotebookConfig

    try:
        nb_cfg = NotebookConfig.from_yaml(nb_cfg_path)
    except Exception:
        return []

    exported: list[str] = []
    build_nb = ctx.build_dir / "notebooks"
    fmt = nb_cfg.publish.format  # "html" or "myst"

    for nb_entry in nb_cfg.entries:
        py_path = ctx.flow_dir / nb_entry.path
        name = py_path.stem

        from pipeio.notebook.lifecycle import _nb_output_paths
        ipynb_path, myst_path = _nb_output_paths(py_path)

        # Explore notebooks are never published by default
        kind = getattr(nb_entry, "kind", "") or ""
        if kind in ("investigate", "explore") and not nb_entry.publish_html and not nb_entry.publish_myst:
            continue

        if nb_entry.publish_html or (fmt == "html" and (nb_entry.publish_html or nb_entry.publish_myst)):
            if ipynb_path.exists():
                build_nb.mkdir(parents=True, exist_ok=True)
                out = build_nb / f"{name}.html"
                if _is_stale(ipynb_path, out):
                    _nbconvert_html(ipynb_path, out)
                exported.append(str(out))

        if nb_entry.publish_myst and fmt == "myst":
            if myst_path.exists():
                build_nb.mkdir(parents=True, exist_ok=True)
                out = build_nb / f"{name}.md"
                if _is_stale(myst_path, out):
                    shutil.copy2(myst_path, out)
                exported.append(str(out))

    # Generate index.md listing in .build/notebooks/
    if build_nb.is_dir():
        nb_files = sorted(
            f for f in build_nb.iterdir()
            if f.is_file() and f.suffix in (".html", ".md") and f.name != "index.md"
        )
        if nb_files:
            nb_index = build_nb / "index.md"
            lines = [_AUTO_GENERATED_HEADER.rstrip(), f"# Notebooks — {ctx.entry.name}", ""]
            for f in nb_files:
                title = f.stem.replace("-", " ").replace("_", " ").title()
                lines.append(f"- [{title}]({f.name})")
            lines.append("")
            nb_index.write_text("\n".join(lines), encoding="utf-8")
            exported.append(str(nb_index))

    return exported


# ---------------------------------------------------------------------------
# Phase 2: Collectors — pure file copiers
# ---------------------------------------------------------------------------

class DocsCollector:
    """Copy hand-written docs from ``{flow}/docs/`` to the output tree.

    Routes mod facet directories (containing theory.md/spec.md/delta.md)
    into ``mods/{mod}/``. Falls back to ``overview.md`` as the flow
    index when no source ``index.md`` exists (legacy convention).
    """

    def collect(self, ctx: CollectContext) -> list[str]:
        collected: list[str] = []
        flow_docs = ctx.flow_dir / "docs"
        if not flow_docs.is_dir():
            return collected

        # Detect mod subdirectories (contain theory.md or spec.md)
        mod_dirs = {
            d.name for d in flow_docs.iterdir()
            if d.is_dir() and any(
                (d / f).exists() for f in ("theory.md", "spec.md", "delta.md")
            )
        }
        has_source_index = (flow_docs / "index.md").is_file()
        for src_file in sorted(flow_docs.rglob("*")):
            if not src_file.is_file():
                continue
            rel = src_file.relative_to(flow_docs)
            parts = rel.parts
            # Route mod facet dirs into mods/ subdirectory
            if parts and parts[0] in mod_dirs:
                dst = ctx.target / "mods" / rel
            # overview.md at flow root → use as index only when no
            # source index.md exists; otherwise keep as separate page
            elif rel == Path("overview.md") and not has_source_index:
                dst = ctx.target / "index.md"
            else:
                dst = ctx.target / rel
            if _is_stale(src_file, dst):
                _copy_with_header(src_file, dst, ctx.root)
            collected.append(str(dst))

        return collected


class NotebookCollector:
    """Copy pre-built notebook artifacts from ``.build/notebooks/`` to the output tree.

    Expects ``export_notebooks()`` to have already generated HTML/MyST
    into ``{flow}/.build/notebooks/``. This collector is a pure copier.
    """

    def collect(self, ctx: CollectContext) -> list[str]:
        collected: list[str] = []
        build_nb = ctx.build_dir / "notebooks"
        if not build_nb.is_dir():
            return collected

        nb_target = ctx.target / "notebooks"
        for src in sorted(build_nb.iterdir()):
            if not src.is_file():
                continue
            if src.suffix not in (".html", ".md"):
                continue
            dst = nb_target / src.name
            if src.suffix == ".html":
                # HTML files are copied as-is (no source header)
                if _is_stale(src, dst):
                    nb_target.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(src, dst)
            else:
                # .md files get the generated header
                if _is_stale(src, dst):
                    nb_target.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(src, dst)
            collected.append(str(dst))

        return collected


class DagCollector:
    """Copy pre-built DAG SVG to the output tree and embed in the flow overview.

    Checks ``.build/dag.svg`` first (from ``export_dag``), then
    ``{flow}/dag.svg`` (legacy / publish.yml convention).  After copying,
    appends a DAG section to ``index.md`` if it exists but doesn't already
    reference the SVG.
    """

    def collect(self, ctx: CollectContext) -> list[str]:
        dag_dst = ctx.target / "dag.svg"

        # Prefer .build/dag.svg (from export phase)
        dag_src = ctx.build_dir / "dag.svg"
        if not dag_src.exists():
            # Backward compat: flow-level dag.svg (publish.yml convention)
            if ctx.publish.dag:
                dag_src = ctx.flow_dir / "dag.svg"

        if not dag_src.exists():
            return []

        if _is_stale(dag_src, dag_dst):
            ctx.target.mkdir(parents=True, exist_ok=True)
            shutil.copy2(dag_src, dag_dst)

        return [str(dag_dst)]


class ReportCollector:
    """Copy Snakemake report HTML and generate a link page.

    Gated by ``publish.report``. Searches for report.html in the
    derivatives directory first, then the flow directory.
    """

    def collect(self, ctx: CollectContext) -> list[str]:
        if not ctx.publish.report:
            return []

        collected: list[str] = []
        report_candidates = [
            ctx.root / "derivatives" / ctx.entry.name / "report.html",
            ctx.flow_dir / "report.html",
        ]
        report_src = next((r for r in report_candidates if r.exists()), None)
        if report_src is None:
            return collected

        ctx.target.mkdir(parents=True, exist_ok=True)
        # Copy full HTML for local serving
        dst_html = ctx.target / "report.html"
        if _is_stale(report_src, dst_html):
            shutil.copy2(report_src, dst_html)
        collected.append(str(dst_html))
        # Markdown summary that links to the local copy
        dst_md = ctx.target / "report.md"
        dst_md.write_text(
            _AUTO_GENERATED_HEADER +
            f"# Report — {ctx.entry.name}\n\n"
            f"[Open full Snakemake report](report.html)\n",
            encoding="utf-8",
        )
        collected.append(str(dst_md))
        return collected


class ScriptsCollector:
    """Generate a script index page from ``{flow}/scripts/*.py``.

    Gated by ``publish.scripts``.
    """

    def collect(self, ctx: CollectContext) -> list[str]:
        if not ctx.publish.scripts:
            return []

        scripts_dir = ctx.flow_dir / "scripts"
        if not scripts_dir.is_dir():
            return []

        script_files = sorted(scripts_dir.glob("*.py"))
        if not script_files:
            return []

        ctx.target.mkdir(parents=True, exist_ok=True)
        dst = ctx.target / "scripts.md"
        dst.write_text(
            _generate_scripts_index(
                ctx.entry.name, script_files, ctx.flow_dir, ctx.root
            ),
            encoding="utf-8",
        )
        return [str(dst)]


class IndexCollector:
    """Generate a stub ``index.md`` if no other collector provided one.

    Always runs last in the collector chain.  When ``dag.svg`` is present
    in the target directory (copied by ``DagCollector``), the generated
    stub embeds it.
    """

    def collect(self, ctx: CollectContext) -> list[str]:
        flow_index = ctx.target / "index.md"
        if flow_index.exists():
            return []

        ctx.target.mkdir(parents=True, exist_ok=True)
        lines = [
            _AUTO_GENERATED_HEADER.rstrip(),
            f"# {ctx.entry.name}",
            "",
            "Pipeline flow documentation.",
        ]
        # Embed DAG if available (DagCollector runs before IndexCollector)
        if (ctx.target / "dag.svg").exists():
            lines.extend(["", "## DAG", "", "![DAG](dag.svg)"])
        lines.append("")
        flow_index.write_text("\n".join(lines), encoding="utf-8")
        return [str(flow_index)]


# ---------------------------------------------------------------------------
# Collector chain — order matters (IndexCollector must be last)
# ---------------------------------------------------------------------------

_COLLECTORS: list[Collector] = [
    DocsCollector(),
    NotebookCollector(),
    DagCollector(),
    ReportCollector(),
    ScriptsCollector(),
    IndexCollector(),
]


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def _find_registry(root: Path) -> Path | None:
    """Locate the pipeline registry, checking .projio/pipeio/ first."""
    from pipeio.registry import find_registry
    return find_registry(root)


def docs_collect(root: Path, *, export: bool = True) -> list[str]:
    """Collect flow-local docs and notebook outputs into ``docs/pipelines/``.

    Two-phase pipeline:

    1. **Export** (when ``export=True``): generate artifacts into each
       flow's ``.build/`` directory — DAG SVGs via snakemake, notebook
       HTML via nbconvert.
    2. **Collect**: run the collector chain to copy hand-written docs,
       pre-built exports, reports, and generated indexes into the
       output tree.

    Pass ``export=False`` to skip generation when exports were already
    produced independently (e.g. via MCP tools or CI).

    Returns list of collected file paths.
    """
    from pipeio.registry import PipelineRegistry

    registry_path = _find_registry(root)
    if registry_path is None:
        return []

    registry = PipelineRegistry.from_yaml(registry_path)
    docs_base = root / "docs" / "pipelines"
    collected: list[str] = []

    # Generate top-level index.md for pipelines section
    pipelines_index = docs_base / "index.md"
    if not pipelines_index.exists():
        docs_base.mkdir(parents=True, exist_ok=True)
        flow_names = [f.name for f in registry.list_flows()]
        lines = [_AUTO_GENERATED_HEADER.rstrip(), "# Pipelines", ""]
        if flow_names:
            for name in flow_names:
                lines.append(f"- [{name}]({name}/index.md)")
        else:
            lines.append("No flows registered yet.")
        lines.append("")
        pipelines_index.write_text("\n".join(lines), encoding="utf-8")
        collected.append(str(pipelines_index))

    # Collect pipeline-level architecture doc
    _first = next(iter(registry.list_flows()), None)
    if _first is not None:
        _first_code = Path(_first.code_path)
        if not _first_code.is_absolute():
            _first_code = root / _first_code
        pipelines_dir = _first_code.parent
    else:
        pipelines_dir = root / "code" / "pipelines"
    arch_src = pipelines_dir / "architecture.md"
    if arch_src.is_file():
        arch_dst = docs_base / "architecture.md"
        arch_dst.parent.mkdir(parents=True, exist_ok=True)
        text = arch_src.read_text(encoding="utf-8")
        text = _normalize_dir_links(text)
        text = _rewrite_mermaid_click_links(text)
        rel = arch_src.relative_to(root)
        header = _GENERATED_HEADER.format(source=rel)
        arch_dst.write_text(header + text, encoding="utf-8")
        collected.append(str(arch_dst))

    # Process each flow
    for entry in registry.list_flows():
        flow_dir = Path(entry.code_path)
        if not flow_dir.is_absolute():
            flow_dir = root / flow_dir
        if not flow_dir.is_dir():
            continue

        # Load publish config once per flow
        pub_path = flow_dir / "publish.yml"
        try:
            pub_cfg = PublishConfig.from_yaml(pub_path) if pub_path.exists() else PublishConfig()
        except Exception:
            pub_cfg = PublishConfig()

        ctx = CollectContext(
            entry=entry,
            flow_dir=flow_dir,
            target=docs_base / entry.name,
            root=root,
            publish=pub_cfg,
        )

        # Phase 1: Export — generate artifacts into .build/
        if export:
            export_dag(ctx)
            export_notebooks(ctx)

        # Phase 2: Collect — pure file copying
        for collector in _COLLECTORS:
            collected.extend(collector.collect(ctx))

    # Write docs/pipelines/mkdocs.yml for monorepo plugin
    if collected:
        docs_nav(root, write=True)
        sub_mkdocs = docs_base / "mkdocs.yml"
        if sub_mkdocs.exists():
            collected.append(str(sub_mkdocs))

    return collected


# ---------------------------------------------------------------------------
# Staleness helper
# ---------------------------------------------------------------------------

def _is_stale(src: Path, dst: Path) -> bool:
    """Return True if *dst* is missing or older than *src*."""
    if not dst.exists():
        return True
    return src.stat().st_mtime > dst.stat().st_mtime


# ---------------------------------------------------------------------------
# DAG helpers
# ---------------------------------------------------------------------------

def _generate_dag_svg(
    root: Path, entry: Any, snakefile: Path,
) -> str | None:
    """Generate a rulegraph SVG via snakemake + graphviz. Returns SVG string or None."""
    import shutil

    if not shutil.which("dot"):
        return None

    flow_dir = snakefile.parent

    # Resolve snakemake command
    smk_cmd = _resolve_snakemake_for_docs()

    cmd = [
        *smk_cmd,
        "--snakefile", str(snakefile),
        "--directory", str(flow_dir),
        "--rulegraph",
    ]

    result = subprocess.run(
        cmd, capture_output=True, text=True, cwd=str(root), timeout=60, check=False,
    )
    if result.returncode != 0:
        return None

    dot_output = result.stdout
    if not dot_output.strip():
        return None

    svg_result = subprocess.run(
        ["dot", "-Tsvg"], input=dot_output, capture_output=True,
        text=True, timeout=30, check=False,
    )
    if svg_result.returncode != 0:
        return None

    return svg_result.stdout


def _resolve_snakemake_for_docs() -> list[str]:
    """Find snakemake for DAG generation during docs_collect."""
    import shutil

    binary = shutil.which("snakemake")
    if binary:
        return [binary]

    # Try common conda env names
    for env in ("cogpy", "snakemake"):
        for base in ("/storage/share/python/environments/Anaconda3",):
            for rel in ("condabin/conda", "bin/conda"):
                conda = Path(base) / rel
                if conda.is_file():
                    return [str(conda), "run", "-n", env, "snakemake"]

    return ["snakemake"]


# ---------------------------------------------------------------------------
# Nav generation
# ---------------------------------------------------------------------------

def docs_nav(root: Path, *, write: bool = True) -> str:
    """Generate nav for ``docs/pipelines/`` and optionally write the monorepo sub-mkdocs.yml.

    When ``write=True`` (default), writes ``docs/pipelines/mkdocs.yml`` — a
    standalone MkDocs config consumed by the ``mkdocs-monorepo-plugin`` via
    ``!include ./docs/pipelines/mkdocs.yml`` in the root ``mkdocs.yml``.

    Always returns the generated YAML string (the nav fragment for legacy use).
    """
    docs_root = root / "docs"
    docs_base = docs_root / "pipelines"
    if not docs_base.exists():
        return "# No docs/pipelines/ directory found.\n"

    flow_navs: list[dict[str, Any]] = []

    for flow_dir in sorted(d for d in docs_base.iterdir() if d.is_dir()):
        flow_entries: list[dict[str, Any]] = []

        # index.md first
        idx = flow_dir / "index.md"
        if idx.exists():
            flow_entries.append(
                {"Overview": str(idx.relative_to(docs_base))}
            )

        # other .md files (excluding index; overview is included when it
        # exists as a separate page alongside index.md)
        for md in sorted(flow_dir.glob("*.md")):
            if md.name == "index.md":
                continue
            title = md.stem.replace("-", " ").replace("_", " ").title()
            flow_entries.append(
                {title: str(md.relative_to(docs_base))}
            )

        # notebooks subdirectory
        nb_dir = flow_dir / "notebooks"
        if nb_dir.is_dir():
            nb_entries: list[dict[str, Any]] = []
            # Use index.md as landing page if present
            nb_idx = nb_dir / "index.md"
            if nb_idx.exists():
                nb_entries.append(
                    {"Overview": str(nb_idx.relative_to(docs_base))}
                )
            for f in sorted(nb_dir.iterdir()):
                if f.name == "index.md":
                    continue
                if f.suffix in (".html", ".md") and f.is_file():
                    title = f.stem.replace("-", " ").replace("_", " ").title()
                    nb_entries.append(
                        {title: str(f.relative_to(docs_base))}
                    )
            if nb_entries:
                flow_entries.append({"Notebooks": nb_entries})

        # mods subdirectory (theory.md, spec.md per mod)
        mods_dir = flow_dir / "mods"
        if mods_dir.is_dir():
            mod_nav_entries: list[dict[str, Any]] = []
            for mod_dir in sorted(d for d in mods_dir.iterdir() if d.is_dir()):
                mod_pages: list[dict[str, str]] = []
                for md in sorted(mod_dir.glob("*.md")):
                    title = md.stem.replace("-", " ").replace("_", " ").title()
                    mod_pages.append(
                        {title: str(md.relative_to(docs_base))}
                    )
                if mod_pages:
                    mod_nav_entries.append({mod_dir.name: mod_pages})
            if mod_nav_entries:
                flow_entries.append({"Modules": mod_nav_entries})

        if flow_entries:
            flow_navs.append({flow_dir.name: flow_entries})

    if not flow_navs:
        return "# docs/pipelines/ exists but contains no docs.\n"

    # Insert architecture.md at the top if present
    arch = docs_base / "architecture.md"
    if arch.exists():
        flow_navs.insert(0, {"Architecture": "architecture.md"})

    # Build the sub-mkdocs.yml for monorepo plugin
    sub_config = {
        "site_name": "pipelines",
        "docs_dir": ".",
        "nav": flow_navs,
    }
    sub_yaml = yaml.dump(sub_config, sort_keys=False, default_flow_style=False)

    if write:
        sub_mkdocs = docs_base / "mkdocs.yml"
        sub_mkdocs.write_text(sub_yaml, encoding="utf-8")

    # Also return the legacy fragment format
    fragment = [{"Pipelines": flow_navs}]
    return yaml.dump(fragment, sort_keys=False, default_flow_style=False)


# ---------------------------------------------------------------------------
# Other helpers
# ---------------------------------------------------------------------------

def _generate_scripts_index(
    flow_name: str,
    script_files: list[Path],
    flow_dir: Path,
    root: Path,
) -> str:
    """Generate a markdown script index."""
    lines = [
        _AUTO_GENERATED_HEADER.rstrip(),
        f"# Scripts — {flow_name}",
        "",
        "| Script | Description |",
        "|--------|-------------|",
    ]
    for sf in script_files:
        rel = sf.relative_to(root)
        # Extract docstring (first line of triple-quoted string)
        desc = ""
        try:
            text = sf.read_text(encoding="utf-8")
            if text.startswith('"""') or text.startswith("'''"):
                end = text.find('"""', 3) if text.startswith('"""') else text.find("'''", 3)
                if end > 0:
                    desc = text[3:end].strip().split("\n")[0]
        except Exception:
            pass
        # Use code-formatted text instead of links (scripts are outside docs_dir)
        lines.append(f"| `{sf.name}` | {desc} |")
    lines.append("")
    return "\n".join(lines)


def _nbconvert_html(nb_path: Path, output: Path) -> None:
    """Convert a notebook to HTML."""
    output.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "jupyter", "nbconvert",
            "--to", "html",
            str(nb_path),
            "--output", str(output.name),
            "--output-dir", str(output.parent),
        ],
        check=True,
    )
